### ISSUE TITLE
Ошибка при запуске

### ISSUE THREAD

**Issue by GoodBoy962** [MinterOne/watchdog#1]
После обновления на блокчейна минтер на 1.2.1 
при запуске получаю ошибку

(node:20447) UnhandledPromiseRejectionWarning: Error: timeout of 3000ms exceeded
    at createError (/root/watchdog/node_modules/minter-js-sdk/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/root/watchdog/node_modules/minter-js-sdk/node_modules/axios/lib/adapters/http.js:264:16)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at RedirectableRequest.emit (events.js:208:7)
    at Timeout._onTimeout (/root/watchdog/node_modules/minter-js-sdk/node_modules/follow-redirects/index.js:166:13)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
(node:20447) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:20447) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:20447) UnhandledPromiseRejectionWarning: Error: timeout of 3000ms exceeded
    at createError (/root/watchdog/node_modules/minter-js-sdk/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/root/watchdog/node_modules/minter-js-sdk/node_modules/axios/lib/adapters/http.js:264:16)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at RedirectableRequest.emit (events.js:208:7)
    at Timeout._onTimeout (/root/watchdog/node_modules/minter-js-sdk/node_modules/follow-redirects/index.js:166:13)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
(node:20447) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:20447) UnhandledPromiseRejectionWarning: Error: timeout of 3000ms exceeded
    at createError (/root/watchdog/node_modules/minter-js-sdk/node_modules/axios/lib/core/createError.js:16:15)
    at RedirectableRequest.handleRequestTimeout (/root/watchdog/node_modules/minter-js-sdk/node_modules/axios/lib/adapters/http.js:264:16)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at RedirectableRequest.emit (events.js:208:7)
    at Timeout._onTimeout (/root/watchdog/node_modules/minter-js-sdk/node_modules/follow-redirects/index.js:166:13)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
(node:20447) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)

**Comment by ingria** [comment]
Эта ошибка означает, что ваше API не смогло ответить за отведённый промежуток времени (по умолчанию этот период составляет 3 секунды). Проверьте, работает ли API и правильно ли указан адрес в конфиге.

Обратите внимание, что адрес API нужно указывать вместе с префиксом (например, `http://127.0.0.1:8843/v2/`).

Если API работает, но слишком медленно, можно увеличить период таймаута (`NODE_API_TIMEOUT_MS=10000` в `.env` увеличит таймаут до 10 секунд).

**Comment by GoodBoy962** [comment]
Указано следующее: NODE_API_URL=https://api.minter.one/v2/
При этом например запрос GET https://api.minter.one/v2/validators отвечает за доли секунд.
